export const DELETE_ITEM = 'DELETE_ITEM';
export const ADD_ITEM = 'ADD_ITEM';
export const QUANTITY_INCREASE = 'QUANTITY_INCREASE';
export const QUANTITY_DECREASE = 'QUANTITY_INCREASE';
export const MINIMUM_INCREASE = 'MINIMUM_INCREASE';
export const MINIMUM_DECREASE = 'MINIMUM_DECREASE';
export const ADD_PURCHASE = 'ADD_PURCHASE';
